collection_name: agent
persist_directory: chroma_db
k: 10
data_path: data
md5_hex_store: md5.text
allow_knowledge_file_type: ["txt", "pdf", "csv"]

chunk_size: 800
chunk_overlap: 120
separators: ["\n\n", "\n", ".", "!", "?", "。", "！", "？", " ", ""]
